export const pricingCards = [
    {
      title: 'Fully fucntional Website',
      description: 'We will provide fully fucntonal website for your business and helping it grow online. It will help you to generate customers online.',
      price: 'Free',
      duration: '',
      highlight: 'Key features',
      features: ['3 Sub accounts', '2 Team members', 'Unlimited pipelines'],
      priceId: '',
    },
    {
      title: 'CRM',
      description: 'Customer Relationship management will help to improve customer satisfaction, streamline processes, and ultimately drive sales and growth.',
      price: '$199',
      duration: 'month',
      highlight: 'Key features',
      features: ['Rebilling', '24/7 Support team'],
      priceId: 'price_1OYxkqFj9oKEERu1KfJGWxgN',
    },
    {
      title: 'Reputation Management',
      description: 'It will help maintain the repution of your business which will attraction more customers and make your business rank higher on Google.',
      price: '$49',
      duration: 'month',
      highlight: 'Everything in Starter, plus',
      features: ['Unlimited Sub accounts', 'Unlimited Team members'],
      priceId: 'price_1OYxkqFj9oKEERu1NbKUxXxN',
    },
    {
        title: 'Online Booking',
        description: 'Customers will be able to book appointments online resulting in customer satisfaction and get more customers then ever before.',
        price: '$49',
        duration: 'month',
        highlight: 'Everything in Starter, plus',
        features: ['Unlimited Sub accounts', 'Unlimited Team members'],
        priceId: 'price_1OYxkqFj9oKEERu1NbKUxXxN',
      },
      {
        title: 'Marketing',
        description: 'It will also help your business market online with the help of emails and etc.',
        price: '$49',
        duration: 'month',
        highlight: 'Everything in Starter, plus',
        features: ['Unlimited Sub accounts', 'Unlimited Team members'],
        priceId: 'price_1OYxkqFj9oKEERu1NbKUxXxN',
      },
      {
        title: 'Tracking & Analytics',
        description: 'Track your business growth and statitics all at one place.',
        price: '$49',
        duration: 'month',
        highlight: 'Everything in Starter, plus',
        features: ['Unlimited Sub accounts', 'Unlimited Team members'],
        priceId: 'price_1OYxkqFj9oKEERu1NbKUxXxN',
      },
      {
        title: 'And many more...',
        description: 'Many other stuff which will help your business grow rapidly.',
        price: '$49',
        duration: 'month',
        highlight: 'Everything in Starter, plus',
        features: ['Unlimited Sub accounts', 'Unlimited Team members'],
        priceId: 'price_1OYxkqFj9oKEERu1NbKUxXxN',
      },
]